#!/usr/bin/env bash

if [ -z "$DIR_STACK" ]; then
  echo 'DIR_STACK не найден'
else
  current_dir=${DIR_STACK%% *}
  dir=${${DIR_STACK#$current_dir }%% *}

  if [ -d "$dir" ]; then
    cd $dir
    DIR_STACK=${DIR_STACK#$current_dir }
    echo $DIR_STACK
  else
    echo "Остаемся в $PWD"
  fi
fi
