#!/usr/bin/env bash

if [ ${#DIR_STACK[@]} -eq 0 ]; then
  echo 'DIR_STACK пуст'
else
  let last_index=0

  for element in ${DIR_STACK[@]}; do
    if [[ -n "$element" && "$element" != " " ]]; then
      (( last_index++ ))
    fi
  done

  dir=${DIR_STACK[(( $last_index-1 ))]}

  if [ -d "$dir" ]; then
    cd $dir
    unset 'DIR_STACK[$last_index]'
    echo "${DIR_STACK[*]}"
  else
    echo "Остаемся в $PWD"
  fi
fi
