#!/usr/bin/env bash

dir=$1

if [ ${#DIR_STACK[@]} -eq 0 ]; then
  DIR_STACK+=("$PWD")
fi

if [ -d "$dir" ]; then
  full_dir="$PWD/${dir#/}"

  let next_index=${#DIR_STACK[@]}+1
  DIR_STACK[$next_index]=$full_dir

  cd $full_dir

  echo "${DIR_STACK[*]}"
else
  echo "Остаемся в $PWD"
fi

export DIR_STACK